// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH77jBwdMdilZKCC1LUf3HLDsYOpzE-4E',
    appId: '1:709300299077:web:48c1fee6aa66af13bdca2c',
    messagingSenderId: '709300299077',
    projectId: 'insure-48e10',
    authDomain: 'insure-48e10.firebaseapp.com',
    storageBucket: 'insure-48e10.appspot.com',
    measurementId: 'G-EHCHD7J3FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVwmjiaauBEOWaqViqLl9HkupHunfitU',
    appId: '1:709300299077:android:de856c17e3a7084dbdca2c',
    messagingSenderId: '709300299077',
    projectId: 'insure-48e10',
    storageBucket: 'insure-48e10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3i3XAo6y3g3T--xDUVyNtQYz1bFgxdvU',
    appId: '1:709300299077:ios:1e70ec4dd6b62526bdca2c',
    messagingSenderId: '709300299077',
    projectId: 'insure-48e10',
    storageBucket: 'insure-48e10.appspot.com',
    iosClientId: '709300299077-qs9ojcp2euobpfrn9bqoqvaqc2abt823.apps.googleusercontent.com',
    iosBundleId: 'com.example.insure',
  );
}
